# Generated by Django 3.1.4 on 2021-01-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='firebase_id',
            new_name='name',
        ),
    ]
