# Generated by Django 3.1.4 on 2021-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='temp_url',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlpY1LuhHbn1l4vToIo7VH9I6K8M2AKFrBp14LzW6PUygfgf18FyHuEVuwCm3iQ-WlCqaYiqF-g8A&usqp=CAc', max_length=2083),
            preserve_default=False,
        ),
    ]
