# Generated by Django 3.1.4 on 2021-01-08 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tag_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='intensity',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
