# Generated by Django 3.1.4 on 2021-01-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pic_temp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='temp_url',
            field=models.TextField(default='https://picsum.photos/seed/picsum/200/300', max_length=100000),
            preserve_default=False,
        ),
    ]
